title: Daniel More # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior leader with 20+ years driving advanced forecasting, optimization, and large-scale analytics across global, high-complexity supply chains. Skilled in developing predictive models, building automated data pipelines, and operationalizing analytics for real-time decision-making. 
  <br><br>
  Experience leading cross-functional teams. Hands-on Python and SQL practitioner with a track record designing optimization logic, statistical forecasting models, and scenario-based decision frameworks used across multiple regions.  
  <br><br>
  Masterâ€™s candidate in Data Science at Harvard and Teaching Fellow supporting data science courses.
  <br><br>
  <a href="https://www.linkedin.com/in/danielmoretorres/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


